[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "Archives"
  url = "post/rich-content/"
  weight = -109

# Submenus are done this way: parent -> identifier
[[main]]
  name = "Links"
  identifier = "Links"
  weight = -108
[[main]]
  parent = "Links"
  name = "AWS"
  url = "https://aws.amazon.com/"
[[main]]
  parent = "Links"
  name = "Kubernetes"
  url = "https://kubernetes.io/"
[[main]]
  parent = "Links"
  name = "Docker"
  url = "https://www.docker.com/"
[[main]]
  parent = "Links"
  name = "Terraform"
  url = "https://www.terraform.io/"
[[main]]
  parent = "Links"
  name = "Ansible"
  url = "https://docs.ansible.com/"
[[main]]
  name = "About"
  url = "about/"
  weight = -107

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/asmodeus70"
[[social]]
  name = "twitter"
  type = "social"
  weight = 2
  url = "https://twitter.com/neilradley"
[[social]]
  name = "linkedin"
  type = "social"
  weight = 3
  url = "https://www.linkedin.com/in/neil-radley-071076b1/"
[[social]]
  name = "rss"
  type = "social"
  weight = 4
  url = "index.xml"

# other supported social links
# name = "youtube"
# url = "https://www.youtube.com/#"
# name = "facebook"
# url = "https://facebook.com/#"
# name = "instagram"
# url = "https://instagram.com/#"
# name = "stackoverflow"
# url = "https://stackoverflow.com/#"
# name = "gitlab"
# url = "https://gitlab.com/#"